project_name: bugg-mic-r5
zip_file: bugg-mic-r5.zip
project_dir: ./src
output_dir: ./build
layers: F.Cu, B.Cu, F.Silkscreen, B.Silkscreen, F.Mask, B.Mask, F.Paste, B.Paste, Edge.Cuts
bom_fields: Reference, ${QUANTITY}, Value, Voltage, Tempco, Tolerance, Footprint, Manufacturer, MPN, Mouser, Digikey
bom_labels: Reference, Qty, Value, Voltage, Tempco, Tolerance, Footprint, Manufacturer, MPN, Mouser, Digikey
bom_groupby: Value, Footprint, Voltage, Tempco, Tolerance
extra_files: src/README.txt
